Added filters for second hand bicycles and DIY repair to bike_shop layer.
pietervdvn/MapComplete pull request #1395
Opened 2023-04-30 20:57 UTC by brunnerpaul

This addresses the following points from #1387 : 

- adds service:bicycle:diy as a filter 
- adds service:bicycle:second_hand

It does not include service:bicycle:ebike_maintenance for reasons to be outlined in the issue.

2023-04-30 21:14 UTC, pietervdvn commented on assets/layers/bike_shop/bike_shop.json
> +      "open_now"
There is no need to wrap a single string into braces - this is not valid JSON.

2023-04-30 21:16 UTC, pietervdvn commented on assets/layers/bike_shop/bike_shop.json
> +        {
The 'question'-block appears twice here. You can drop the first one

2023-04-30 21:56 UTC, pietervdvn commented
[Screencast from 30-04-23 23:35:42.webm](https://user-images.githubusercontent.com/1466478/235377368-181986ad-369c-42ed-8f48-58eb5d53529a.webm)

Preview of the new filter functionality in action.

The first block in the filter is always the one where no filters are applied. It should thus read something like 'all shops, whether or not they offer DIY repair'.

Second, I'm not very fond of the 'no information known'-option. I understand that you want to create a todo-list of all shops that still need surveying, but this works poorly as all filters are applied simultaneously. For example, if you were to check both 'DIY-service not known' *and* 'sells second hand bikes not known', this will result in _only_ showing those shops where _both_ properties are not known. Shops where one property is known and the other not will _not_ be shown - thus missing many of the shops that you'd want to survey. Up till now, missing data was interpreted as 'no' in most of the filters, thus omitting them from view to avoid false positives.

By the way: by creating a 'todo-list' of shops to survey: MapComplete has always been on the edge of being a _consumer map_ and and _contributing tool_. (Contrast this with StreetComplete, which is 100% a contributing tool and is by design this 'todo-list'). I feel that introducing this 'todo-list'-approach will be confusing for some non-technical (non-contributing) users and has no added value for them. I'm however open to discuss this or another approach so that power users _can_ use this as an actual contributing tool, e.g. after setting a flag in the user settings.



We should also be careful with wording. For example, `Only sells second hand bicycles
` is probably intended as a shop which sells bikes and those sold bikes all are second hand (i.e. no newly produced bicycles are sold there). But the wording might imply that that shop does not offer any other service, such as bike repair.

From the perspective of someone who is searching to buy a second hand bike, the option 'only second hand bikes' is a bit weird - they would rather have an option highlighting all the shops where one can by a second hand bike - even if this would show shops where one could also buy a totally new bike.

I would thus propose to simplify the filter and stick to just a single option: 'does sell second hand bikes', corresponding with `service:bicycle:second_hand=yes` or `service:bicycle:second_hand=only` and omitting the 'unknown'-filter.

2023-04-30 21:56 UTC, pietervdvn requested changes
See conversation

2023-05-01 05:21 UTC, maphouse commented
Nice work @brunnerpaul ! this is super exciting to see. As you can see in [this transit mapcomplete theme](https://mapcomplete.osm.be/transit.html?z=17&lat=45.49514&lon=-73.5606&language=en&filter-shelter=true&filter-bench=true&filter-bin=&filter-tactile_paving=&layer-transit_routes=false&layer-bike_parking=false&layer-parking=false&layer-shelter=false#filters), filters there are additive: as the user selects more of them, the selection/search becomes more and more refined. I think this would work well here such that only the below is necessary:
![image](https://user-images.githubusercontent.com/4475249/235409141-0ad7bfe0-d756-432d-96f9-4202013f8cf1.png)

By selecting both the highlighted above, we are selecting for shops that both sell used bikes AND offer diy services. If we want to display shops that don't sell second hand bikes, then we simply uncheck that filter (of course, we won't know whether it is because they *don't sell second hand bikes* or whether the shop data is just incomplete... but I think that's ok.

Finally, I'm not sure whether *only* selling used bikes is a necessary filter (it's too bad there isn't a clear distinction between selling used and new bikes within osm, i.e. something like retail_new and retail_used would be more useful than second_hand=only, but that's maybe another conversation).

2023-05-01 05:23 UTC, maphouse commented
> Nice work @brunnerpaul ! this is super exciting to see. As you can see in [this transit mapcomplete theme](https://mapcomplete.osm.be/transit.html?z=17&lat=45.49514&lon=-73.5606&language=en&filter-shelter=true&filter-bench=true&filter-bin=&filter-tactile_paving=&layer-transit_routes=false&layer-bike_parking=false&layer-parking=false&layer-shelter=false#filters), filters there are additive: as the user selects more of them, the selection/search becomes more and more refined. I think this would work well here such that only the below is necessary: ![image](https://user-images.githubusercontent.com/4475249/235409141-0ad7bfe0-d756-432d-96f9-4202013f8cf1.png)
> 
> By selecting both the highlighted above, we are selecting for shops that both sell used bikes AND offer diy services. If we want to display shops that don't sell second hand bikes, then we simply uncheck that filter (of course, we won't know whether it is because they _don't sell second hand bikes_ or whether the shop data is just incomplete... but I think that's ok.
> 
> Finally, I'm not sure whether _only_ selling used bikes is a necessary filter (it's too bad there isn't a clear distinction between selling used and new bikes within osm, i.e. something like retail_new and retail_used would be more useful than second_hand=only, but that's maybe another conversation).

Did not see ur latest commit https://github.com/pietervdvn/MapComplete/pull/1395/commits/11ddee04bff3f929bb77ed2c5743f7aa0342c007, sorry about that

2023-05-01 07:53 UTC, pietervdvn approved these changes

2023-05-01 08:08 UTC, merged

2023-05-01 15:45 UTC, brunnerpaul commented
@maphouse, yes, in the end we kept the filters simple, so no multiple values and no "missing data" option. I think we can find another way to a) communicate to users that missing data might be the cause of an object not showing up and b) encourage them to survey/research and add said data.