Update public_bookcase.json
pietervdvn/MapComplete pull request #810
Opened 2022-05-03 16:56 UTC by danieldegroot2

Fixed #804.

ToDo (optional):
- Decide whether to keep books=children;adults (possibly redundant; may mean the same as leaving it empty)
- Lock values `children`/`adults`(/`children;adults`) (combined choice + string question, like opening hours).

2022-05-03 18:45 UTC, pietervdvn approved these changes

2022-05-05 09:14 UTC, pietervdvn requested changes
Add a multianswer

2022-05-05 09:52 UTC, danieldegroot2 commented on assets/layers/public_bookcase/public_bookcase.json
> +      "freeform": {
Changed to multiAnswer.
(Sidenote: noticed addExtraTags has slightly different formatting with `#` for [valves](https://github.com/pietervdvn/MapComplete/blob/194ee668ae63e3ed7b26d2fece383c172d49470a/assets/layers/bike_repair_station/bike_repair_station.json#L586).)

2022-05-13 00:09 UTC, pietervdvn approved these changes

2022-05-13 00:09 UTC, merged